[package]
name = "lifetimes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "generic"
path = "src/generic_lifetimes/main.rs"

[[bin]]
name = "concrete"
path = "src/concrete_lifetimes/main.rs"

[[bin]]
name = "structs"
path = "src/struct_lifetimes/main.rs"

[dependencies]
rand = "0.8.5"
